import { Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { colors, money } from '../theme';
import { AddButton, Header, SectionTitle, StatusPill } from '../components/UI';

import { useMemo, useState } from 'react';

export default function BookingsScreen({ bookings, cars, onNew, onBookingAction }) {
  const [query,setQuery]=useState('');
  const [filter,setFilter]=useState('All');
  const activeBookings=bookings.filter(item=>!['Cancelled','Completed'].includes(item.status));
  const pickupToday=bookings.filter(item=>item.dates.toLowerCase().startsWith('today')&&!['Cancelled','Completed'].includes(item.status)).length;
  const visibleBookings=useMemo(()=>bookings.filter(item=>{
    const car=cars.find(vehicle=>vehicle.id===item.carId);
    const matchesQuery=(item.customer+' '+item.id+' '+(car?.make||'')+' '+(car?.model||'')).toLowerCase().includes(query.toLowerCase());
    return matchesQuery&&(filter==='All'||item.status===filter);
  }),[bookings,cars,filter,query]);
  return <ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={s.page}>
    <Header eyebrow="RENTTRACK / SCHEDULE" title="Bookings" action={<AddButton onPress={onNew}/>}/>
    <View style={s.summary}><View><Text style={s.big}>{String(activeBookings.length).padStart(2,'0')}</Text><Text style={s.caption}>OPEN BOOKINGS</Text></View><View style={s.divider}/><View><Text style={[s.big,{color:colors.lime}]}>{String(pickupToday).padStart(2,'0')}</Text><Text style={s.caption}>PICKUP TODAY</Text></View></View>
    <View style={s.search}><Text style={s.searchMark}>Q</Text><TextInput value={query} onChangeText={setQuery} style={s.searchInput} placeholder="Search bookings" placeholderTextColor="#6F8979"/></View>
    <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.filters}>{['All','Confirmed','Upcoming','Active','Cancelled','Completed'].map(item=><Pressable key={item} onPress={()=>setFilter(item)} style={[s.filter,filter===item&&s.filterActive]}><Text style={[s.filterText,filter===item&&s.filterTextActive]}>{item}</Text></Pressable>)}</ScrollView>
    <SectionTitle right={visibleBookings.length+' RECORDS'}>SCHEDULED RENTALS</SectionTitle>
    {visibleBookings.map(item=>{const car=cars.find(x=>x.id===item.carId);return <View style={s.booking} key={item.id}><View style={s.avatar}><Text style={s.avatarText}>{item.initials}</Text></View><View style={s.bookingCopy}><View style={s.bookingTop}><Text numberOfLines={1} style={s.customer}>{item.customer}</Text><Text style={s.id}>{item.id}</Text></View><Text numberOfLines={1} style={s.car}>{car?.make} {car?.model} / {car?.plate}</Text><Text numberOfLines={1} style={s.dates}>{item.dates}</Text><View style={s.bookingBottom}><StatusPill status={item.status==='Confirmed'?'Reserved':item.status}/><Text style={s.total}>{money(item.total)}</Text></View>{!['Cancelled','Completed'].includes(item.status)&&<View style={s.actions}>{item.status==='Active'?<Pressable onPress={()=>onBookingAction(item,'complete')} style={s.action}><Text style={s.actionText}>CHECK IN</Text></Pressable>:<Pressable onPress={()=>onBookingAction(item,'checkout')} style={s.action}><Text style={s.actionText}>CHECK OUT</Text></Pressable>}<Pressable onPress={()=>onBookingAction(item,'cancel')} style={s.cancel}><Text style={s.cancelText}>CANCEL</Text></Pressable></View>}</View></View>})}
    {!visibleBookings.length&&<Text style={s.empty}>No bookings match that filter.</Text>}
    <Pressable onPress={onNew} style={s.newBooking}><Text style={s.newPlus}>+</Text><Text style={s.newText}>NEW BOOKING</Text></Pressable>
  </ScrollView>;
}
const s=StyleSheet.create({
 page:{padding:20,paddingBottom:102},summary:{backgroundColor:colors.panel2,borderWidth:1,borderColor:colors.line,borderRadius:15,padding:19,marginBottom:15,flexDirection:'row',gap:23},big:{color:colors.paper,fontSize:29,lineHeight:31,fontWeight:'900'},caption:{color:colors.muted,fontSize:8,letterSpacing:.65,fontWeight:'900',marginTop:4},divider:{width:1,backgroundColor:colors.line},search:{height:48,backgroundColor:colors.panel,borderWidth:1,borderColor:colors.line,borderRadius:13,flexDirection:'row',alignItems:'center',paddingHorizontal:14,marginBottom:12},searchMark:{color:colors.muted,fontSize:12,fontWeight:'900',marginRight:10},searchInput:{flex:1,color:colors.paper,fontSize:14,height:'100%'},filters:{gap:8,paddingBottom:20},filter:{borderRadius:18,borderWidth:1,borderColor:colors.line,paddingVertical:9,paddingHorizontal:13},filterActive:{backgroundColor:colors.lime,borderColor:colors.lime},filterText:{color:colors.muted,fontSize:10,fontWeight:'800'},filterTextActive:{color:colors.dark},booking:{flexDirection:'row',backgroundColor:colors.panel,borderWidth:1,borderColor:colors.line,borderRadius:14,padding:12,marginBottom:9},avatar:{width:38,height:38,borderRadius:11,backgroundColor:colors.orange,alignItems:'center',justifyContent:'center',marginRight:10},avatarText:{color:colors.dark,fontSize:11,fontWeight:'900'},bookingCopy:{flex:1,minWidth:0},bookingTop:{flexDirection:'row',gap:8,alignItems:'baseline'},customer:{flex:1,color:colors.paper,fontSize:15,fontWeight:'800'},id:{color:colors.muted,fontSize:8,letterSpacing:.7,fontWeight:'900'},car:{color:colors.lime,fontSize:10,fontWeight:'700',marginTop:3},dates:{color:colors.muted,fontSize:10,marginTop:4},bookingBottom:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',marginTop:10},total:{color:colors.paper,fontSize:12,fontWeight:'800'},actions:{flexDirection:'row',gap:8,marginTop:10},action:{borderRadius:7,backgroundColor:colors.lime,paddingVertical:8,paddingHorizontal:10},actionText:{color:colors.dark,fontSize:8,fontWeight:'900'},cancel:{borderRadius:7,borderWidth:1,borderColor:colors.red,paddingVertical:7,paddingHorizontal:10},cancelText:{color:colors.red,fontSize:8,fontWeight:'900'},empty:{color:colors.muted,textAlign:'center',marginTop:25},newBooking:{height:78,borderRadius:14,backgroundColor:colors.panel2,borderStyle:'dashed',borderWidth:1,borderColor:colors.line,alignItems:'center',justifyContent:'center',marginTop:3},newPlus:{color:colors.lime,fontSize:22,lineHeight:23},newText:{color:colors.lime,fontSize:9,letterSpacing:1,fontWeight:'900'},
});
